# Generated by Django 4.2.2 on 2024-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "student_id",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสนักศึกษา",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="ชื่อ-สกุล"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "ปกติ"),
                            (2, "โอนย้าย"),
                            (3, "พักการเรียน"),
                            (4, "พ้นสภาพ"),
                            (5, "ลาออก"),
                        ],
                        verbose_name="สถานภาพ",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["student_id"],
            },
        ),
    ]
