# Generated by Django 4.2.2 on 2024-02-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Students",),
    ]
