# Generated by Django 4.2.2 on 2024-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ประกาศ", max_length=255, verbose_name="เรื่อง"
                    ),
                ),
                ("content", models.TextField(verbose_name="เนื้อหา")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="publish_images/",
                        verbose_name="รูปภาพ",
                    ),
                ),
            ],
            options={"verbose_name": "Publish", "verbose_name_plural": "Publishes",},
        ),
    ]
