# Generated by Django 4.2.2 on 2024-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publish",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/publish_images/",
                verbose_name="รูปภาพ",
            ),
        ),
    ]
