# Generated by Django 5.1.3 on 2025-02-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publish",
            name="content",
            field=models.TextField(null=True, verbose_name="เนื้อหา"),
        ),
    ]
