# Generated by Django 4.2.2 on 2024-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_alter_publish_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirm", models.CharField(default="รอตรวจสอบ", max_length=20)),
                (
                    "status",
                    models.ImageField(
                        choices=[(1, "อนุมัติ"), (2, "ไม่อนุมัติ")],
                        default="รอตรวจสอบ",
                        max_length=5,
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
