# Generated by Django 4.2.2 on 2024-02-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_confirm"),
    ]

    operations = [
        migrations.DeleteModel(name="Confirm",),
    ]
