# Generated by Django 4.2.2 on 2024-02-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "student_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="ชื่อ-สกุล"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
