# Generated by Django 4.2.2 on 2024-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="ชื่อผู้ใช้"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="อีเมล")),
                (
                    "student_id",
                    models.IntegerField(max_length=15, verbose_name="รหัสนักศึกษา"),
                ),
            ],
        ),
        migrations.DeleteModel(name="Profile",),
    ]
