# Generated by Django 4.2.2 on 2024-04-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_register_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Register",),
    ]
