# Generated by Django 5.0.4 on 2024-05-24 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date3",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่"
                    ),
                ),
                (
                    "certificate3",
                    models.FileField(
                        default=None,
                        upload_to="certificates2/",
                        verbose_name="อัพโหลดเอกสาร",
                    ),
                ),
                (
                    "status3",
                    models.CharField(
                        choices=[
                            ("pending", "รอการอนุมัติ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ไม่อนุมัติ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Createform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date2",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่"
                    ),
                ),
                (
                    "certificate2",
                    models.FileField(
                        default=None,
                        upload_to="certificates2/",
                        verbose_name="อัพโหลดเอกสาร",
                    ),
                ),
                (
                    "status2",
                    models.CharField(
                        choices=[
                            ("pending", "รอการอนุมัติ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ไม่อนุมัติ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="หัวข้อ")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่"
                    ),
                ),
                ("score", models.IntegerField(verbose_name="จำนวนชั่วโมง")),
                (
                    "certificate",
                    models.FileField(
                        upload_to="certificates/", verbose_name="เอกสารรับรอง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการอนุมัติ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ไม่อนุมัติ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
        ),
    ]
