# Generated by Django 4.2.2 on 2024-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "certification_document",
                    models.FileField(upload_to="certification_documents/"),
                ),
                ("credit_hours", models.IntegerField()),
            ],
        ),
    ]
