# Generated by Django 5.1.3 on 2024-12-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aftercompleted",
            old_name="certificate3",
            new_name="certificate2",
        ),
        migrations.RenameField(
            model_name="createform",
            old_name="certificate2",
            new_name="certificate1",
        ),
    ]
