# Generated by Django 4.2.2 on 2024-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_coop"),
    ]

    operations = [
        migrations.DeleteModel(name="Coop",),
        migrations.AlterField(
            model_name="record",
            name="certificate",
            field=models.FileField(
                upload_to="certificates/", verbose_name="เอกสารรับรอง"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(verbose_name="วันที่"),
        ),
        migrations.AlterField(
            model_name="record",
            name="score",
            field=models.IntegerField(verbose_name="จำนวนชั่วโมง"),
        ),
        migrations.AlterField(
            model_name="record",
            name="title",
            field=models.CharField(max_length=255, verbose_name="หัวข้อ"),
        ),
    ]
