# Generated by Django 4.2.2 on 2024-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_delete_coop_alter_record_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="เหตุผล"),
        ),
        migrations.AddField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[("1", "อนุมัติ"), ("2", "ไม่อนุมัติ")],
                default="1",
                max_length=1,
                verbose_name="สถานะ",
            ),
        ),
    ]
