# Generated by Django 4.2.2 on 2024-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_record_reason_record_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[("confirm", "อนุมัติ"), ("unconfirm", "ไม่อนุมัติ")],
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
