# Generated by Django 4.2.2 on 2024-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_record_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="record", name="reason",),
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการอนุมัติ"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ไม่อนุมัติ"),
                ],
                default="pending",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
