# Generated by Django 4.2.2 on 2024-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_remove_record_reason_alter_record_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Createform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.TextField()),
            ],
        ),
    ]
