# Generated by Django 4.2.2 on 2024-03-27 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_createform"),
    ]

    operations = [
        migrations.RemoveField(model_name="createform", name="field1",),
        migrations.RemoveField(model_name="createform", name="field2",),
        migrations.AddField(
            model_name="createform",
            name="certificate2",
            field=models.FileField(
                default=None, upload_to="certificates2/", verbose_name="อัพโหลดเอกสาร"
            ),
        ),
        migrations.AddField(
            model_name="createform",
            name="date2",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่"
            ),
        ),
        migrations.AddField(
            model_name="createform",
            name="status2",
            field=models.CharField(
                choices=[
                    ("pending", "รอการอนุมัติ"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ไม่อนุมัติ"),
                ],
                default="pending",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
