# Generated by Django 4.2.2 on 2024-04-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0008_remove_createform_field1_remove_createform_field2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="user",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ใช้",
            ),
        ),
    ]
