# Generated by Django 5.0.4 on 2024-04-24 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_createform_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AfterCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date3",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่"
                    ),
                ),
                (
                    "certificate3",
                    models.FileField(
                        default=None,
                        upload_to="certificates2/",
                        verbose_name="อัพโหลดเอกสาร",
                    ),
                ),
                (
                    "status3",
                    models.CharField(
                        choices=[
                            ("pending", "รอการอนุมัติ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ไม่อนุมัติ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=11,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
        ),
    ]
